// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Innovark.Weather.Web.WeatherApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WeatherRecord : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The current_time property</summary>
        public DateTimeOffset? CurrentTime { get; set; }
        /// <summary>The relative_humidity property</summary>
        public int? RelativeHumidity { get; set; }
        /// <summary>The temperature_c property</summary>
        public double? TemperatureC { get; set; }
        /// <summary>The temperature_f property</summary>
        public double? TemperatureF { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Innovark.Weather.Web.WeatherApi.Models.WeatherRecord"/> and sets the default values.
        /// </summary>
        public WeatherRecord()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Innovark.Weather.Web.WeatherApi.Models.WeatherRecord"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Innovark.Weather.Web.WeatherApi.Models.WeatherRecord CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Innovark.Weather.Web.WeatherApi.Models.WeatherRecord();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "current_time", n => { CurrentTime = n.GetDateTimeOffsetValue(); } },
                { "relative_humidity", n => { RelativeHumidity = n.GetIntValue(); } },
                { "temperature_c", n => { TemperatureC = n.GetDoubleValue(); } },
                { "temperature_f", n => { TemperatureF = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("current_time", CurrentTime);
            writer.WriteIntValue("relative_humidity", RelativeHumidity);
            writer.WriteDoubleValue("temperature_c", TemperatureC);
            writer.WriteDoubleValue("temperature_f", TemperatureF);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
