// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Innovark.Weather.Web.WeatherApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WeatherHistoryResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The location property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Innovark.Weather.Web.WeatherApi.Models.LocationInfo? Location { get; set; }
#nullable restore
#else
        public global::Innovark.Weather.Web.WeatherApi.Models.LocationInfo Location { get; set; }
#endif
        /// <summary>The records property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Innovark.Weather.Web.WeatherApi.Models.WeatherRecord>? Records { get; set; }
#nullable restore
#else
        public List<global::Innovark.Weather.Web.WeatherApi.Models.WeatherRecord> Records { get; set; }
#endif
        /// <summary>The requested_time property</summary>
        public DateTimeOffset? RequestedTime { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Innovark.Weather.Web.WeatherApi.Models.WeatherHistoryResponse"/> and sets the default values.
        /// </summary>
        public WeatherHistoryResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Innovark.Weather.Web.WeatherApi.Models.WeatherHistoryResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Innovark.Weather.Web.WeatherApi.Models.WeatherHistoryResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Innovark.Weather.Web.WeatherApi.Models.WeatherHistoryResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "location", n => { Location = n.GetObjectValue<global::Innovark.Weather.Web.WeatherApi.Models.LocationInfo>(global::Innovark.Weather.Web.WeatherApi.Models.LocationInfo.CreateFromDiscriminatorValue); } },
                { "records", n => { Records = n.GetCollectionOfObjectValues<global::Innovark.Weather.Web.WeatherApi.Models.WeatherRecord>(global::Innovark.Weather.Web.WeatherApi.Models.WeatherRecord.CreateFromDiscriminatorValue)?.AsList(); } },
                { "requested_time", n => { RequestedTime = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Innovark.Weather.Web.WeatherApi.Models.LocationInfo>("location", Location);
            writer.WriteCollectionOfObjectValues<global::Innovark.Weather.Web.WeatherApi.Models.WeatherRecord>("records", Records);
            writer.WriteDateTimeOffsetValue("requested_time", RequestedTime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
