import type { StorybookConfig } from "@storybook/react-vite"

const config: StorybookConfig = {
  stories: ["../src/**/*.mdx", "../src/**/*.stories.@(ts|tsx)"],
  addons: [
    "@storybook/addon-a11y",
    "@storybook/addon-docs",
    "@storybook/addon-vitest",
    "msw-storybook-addon",
  ],
  // Serves public/mockServiceWorker.js (generated by `msw init`) so msw-storybook-addon's worker
  // can register itself.
  staticDirs: ["../public"],
  framework: "@storybook/react-vite",
}

export default config
