// <auto-generated/>
#pragma warning disable CS0618
using Innovark.Weather.Web.WeatherApi.Api.V1.Weather.History;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Innovark.Weather.Web.WeatherApi.Api.V1.Weather
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\weather
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WeatherRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The history property</summary>
        public global::Innovark.Weather.Web.WeatherApi.Api.V1.Weather.History.HistoryRequestBuilder History
        {
            get => new global::Innovark.Weather.Web.WeatherApi.Api.V1.Weather.History.HistoryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Innovark.Weather.Web.WeatherApi.Api.V1.Weather.WeatherRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WeatherRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/weather", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Innovark.Weather.Web.WeatherApi.Api.V1.Weather.WeatherRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WeatherRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/weather", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
