// <auto-generated/>
#pragma warning disable CS0618
using Innovark.Weather.Web.WeatherApi.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Innovark.Weather.Web.WeatherApi.Api.V1.Weather.History
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\weather\history
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class HistoryRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Innovark.Weather.Web.WeatherApi.Api.V1.Weather.History.HistoryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HistoryRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/weather/history?date={date}&hour={hour}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Innovark.Weather.Web.WeatherApi.Api.V1.Weather.History.HistoryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HistoryRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/weather/history?date={date}&hour={hour}", rawUrl)
        {
        }
        /// <summary>
        /// Returns the requested hour and the 9 hours before it, newest first. The date and hour are in UTC+7 and must be no later than the current hour and no more than 72 hours before it.
        /// </summary>
        /// <returns>A <see cref="global::Innovark.Weather.Web.WeatherApi.Models.WeatherHistoryResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Innovark.Weather.Web.WeatherApi.Models.HttpValidationProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::Innovark.Weather.Web.WeatherApi.Models.ProblemDetails">When receiving a 502 status code</exception>
        /// <exception cref="global::Innovark.Weather.Web.WeatherApi.Models.ProblemDetails">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Innovark.Weather.Web.WeatherApi.Models.WeatherHistoryResponse?> GetAsync(Action<RequestConfiguration<global::Innovark.Weather.Web.WeatherApi.Api.V1.Weather.History.HistoryRequestBuilder.HistoryRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Innovark.Weather.Web.WeatherApi.Models.WeatherHistoryResponse> GetAsync(Action<RequestConfiguration<global::Innovark.Weather.Web.WeatherApi.Api.V1.Weather.History.HistoryRequestBuilder.HistoryRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Innovark.Weather.Web.WeatherApi.Models.HttpValidationProblemDetails.CreateFromDiscriminatorValue },
                { "502", global::Innovark.Weather.Web.WeatherApi.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "503", global::Innovark.Weather.Web.WeatherApi.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Innovark.Weather.Web.WeatherApi.Models.WeatherHistoryResponse>(requestInfo, global::Innovark.Weather.Web.WeatherApi.Models.WeatherHistoryResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns the requested hour and the 9 hours before it, newest first. The date and hour are in UTC+7 and must be no later than the current hour and no more than 72 hours before it.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Innovark.Weather.Web.WeatherApi.Api.V1.Weather.History.HistoryRequestBuilder.HistoryRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Innovark.Weather.Web.WeatherApi.Api.V1.Weather.History.HistoryRequestBuilder.HistoryRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Innovark.Weather.Web.WeatherApi.Api.V1.Weather.History.HistoryRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Innovark.Weather.Web.WeatherApi.Api.V1.Weather.History.HistoryRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Innovark.Weather.Web.WeatherApi.Api.V1.Weather.History.HistoryRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns the requested hour and the 9 hours before it, newest first. The date and hour are in UTC+7 and must be no later than the current hour and no more than 72 hours before it.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class HistoryRequestBuilderGetQueryParameters 
        {
            /// <summary>Date in UTC+7, e.g. 2026-09-28.</summary>
            [QueryParameter("date")]
            public Date? Date { get; set; }
            /// <summary>Hour in UTC+7, 0–23.</summary>
            [QueryParameter("hour")]
            public int? Hour { get; set; }
        }
    }
}
#pragma warning restore CS0618
